### ISSUE TITLE
My client ID and client secret doesn't seem to work

### ISSUE THREAD

**Issue by johnjullies** [scotch-io/node-booklet-code#2]
This is the output if I use the client_id and client_secret I obtained from Instagram by following the steps from the booklet:  

```
TypeError: C:\Users\j\Github\sample-nodejs-app\ig-app\views\pages\index.ejs:14
    12|         <main>
    13|                 <div class="row">
 >> 14|                         <% grams.forEach(function(gram) { %>
    15|                                 <div class="instagram-pic col-sm-3">
    16|                                         <a href="<%= gram.link %>" target="_blank">
    17|                                                 <img src="<%= gram.images.standard_resolution.url %>" class="img-responsive" alt="">

Cannot read property 'forEach' of undefined
    at eval (eval at <anonymous> (C:\Users\j\Github\sample-nodejs-app\ig-app\node_modules\ejs\lib\ejs.js:464:12), <anonymous>:21:13)
    at returnedFn (C:\Users\j\Github\sample-nodejs-app\ig-app\node_modules\ejs\lib\ejs.js:493:17)
    at View.exports.renderFile [as engine] (C:\Users\j\Github\sample-nodejs-app\ig-app\node_modules\ejs\lib\ejs.js:350:31)
    at View.render (C:\Users\j\Github\sample-nodejs-app\ig-app\node_modules\express\lib\view.js:126:8)
    at tryRender (C:\Users\j\Github\sample-nodejs-app\ig-app\node_modules\express\lib\application.js:639:10)
    at EventEmitter.render (C:\Users\j\Github\sample-nodejs-app\ig-app\node_modules\express\lib\application.js:591:3)
    at ServerResponse.render (C:\Users\j\Github\sample-nodejs-app\ig-app\node_modules\express\lib\response.js:961:7)
    at C:\Users\j\Github\sample-nodejs-app\ig-app\server.js:29:13
    at handle_error (C:\Users\j\Github\sample-nodejs-app\ig-app\node_modules\instagram-node\lib\instagram.js:255:14)
    at C:\Users\j\Github\sample-nodejs-app\ig-app\node_modules\instagram-node\lib\instagram.js:904:16
```

but when I changed the client_id and client_secret to the one in this code repo, it worked. Why is that?

**Comment by johnjullies** [comment]
I hope it's okay that I opened an issue to ask a question.

**Comment by CodeWritingCow** [comment]
Hello John, I have the same problem. Developers might now need an access token to use the Instagram API. This might not affect older apps. I'll give you a holler if I find a solution.

**Comment by CodeWritingCow** [comment]
OK John, here's my solution.
1) Get an access token. Here's how: http://jelled.com/instagram/access-token
2) Add this to your server.js: 

``` javascript
ig.use({ access_token: 'YOUR_ACCESS_TOKEN' });
```

Here's how I rewrote my server.js:

``` javascript
app.get('/', function (req, res) {
    ig.use({ access_token: 'YOUR_ACCESS_TOKEN' });
    ig.media_popular(function (err, medias, remaining, limit) {
        res.render('pages/index', { grams: medias });
    });
});
```

Oh, and remove this from .instagram-pic img inside your style.css

``` css
position: absolute;
```

Otherwise, your app will display the photos in a very ugly manner. Not sure why.

Hope this helps!

**Comment by johnjullies** [comment]
hey @CodeWritingCow , sorry for the very late response! Unfortunately it's still showing the same error even with the access token and additional code that you suggested,

**Comment by CodeWritingCow** [comment]
Hi @johnjullies, did you replace `YOUR_ACCESS_TOKEN` with your new token? That's a mistake that I've made before. Can you post the code for your latest `server.js` here? I can take a look at it and see what you might need to change.

**Comment by johnjullies** [comment]
@CodeWritingCow yes I replaced it with my token. Anyways, here's my latest server.js

``` javascript
// GRAB THE PACKAGES/VARIABLES WE NEED
// ==================================================
var express = require('express');
var app     = express();
var ig      = require('instagram-node').instagram();

// CONFIGURE THE APP
// ==================================================
// tell node where to look for site resources
app.use(express.static(__dirname + '/public'));

// set the view engine to ejs
app.set('view engine', 'ejs');

// configure instagram app with client_id
ig.use({ 
    client_id: '37895f60468e425c884f2501a02a3011',
    client_secret: 'bc214a0263f4458faa21bce1d6a2da9d' 
});

// SET THE ROUTES
// ===================================================
// home page route - popular images
app.get('/', function(req, res) {
        ig.use({ access_token: '231573066.37895f6.664568de11da47e18b943a686880617e' });
    // use the instagram package to get popular media
    ig.media_popular(function(err, medias, remaining, limit) {
        // render the home page and pass in the popular images
        res.render('pages/index', { grams: medias });
    });

});

// START THE SERVER
// ==================================================
app.listen(8080);
console.log('App started! Look at http://localhost:8080');
```

**Comment by CodeWritingCow** [comment]
@johnjullies I tested your code. Two things. 
(1) I forgot to mention this earlier. When we configure the app with `client_id`, we need the access token, too! Like so:

```
// configure instagram app with client_id
ig.use({ access_token: 'YOUR_ACCESS_TOKEN' });
ig.use({ 
    client_id: 'YOUR_CLIENT_ID',
    client_secret: 'YOUR_SECRET' 
});
```

(2) Your access token didn't work. Try using a new one. I tested your server.js with my access token (after doing (1) as described above), and your file worked.

Hope this helps!

**Comment by johnjullies** [comment]
I finally got it to work! I got my new access token tru this site because the one you provided was down: http://instagram.pixelunion.net/

Thanks a lot for your help @CodeWritingCow

**Comment by CodeWritingCow** [comment]
You're welcome @johnjullies! Glad I could help.

**Comment by manash23** [comment]
hey @johnjullies  can u share ur entire code ....m doing the the same thing u did..but even after doing evrything correct in server.js i m getting the same error....help will be appreciated
