### ISSUE TITLE
Instagram returning HTML instead of JSON

### ISSUE THREAD

**Issue by davidwkaiser** [scotch-io/node-booklet-code#6]
When I run the app ,whether from my code base or from a clone, the app fails to authenticate at IG, giving this error: 

{ SyntaxError: Unexpected token < in JSON at position 0
    at Object.parse (native)
    at IncomingMessage.<anonymous> (/Users/test/Desktop/simple_node_app/node_modules/instagram-node/lib/instagram.js:192:27)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
  retry: [Function: retry],
  status_code: 404,
etc, etc...

I tested the token with an API call from the browser, it works when it is standalone, but the server.js file keeps throwing this error. It does not matter whether I use client_id and client_secret or not. I also tried using a variety of different API calls, just in case the paths had changed, no effect. I have been banging my head on this for a while, my gut feel is that it's something to do with versions, but I haven't found it yet. 

Here are my versions: 

  "dependencies": {
    "ejs": "^2.5.6",
    "express": "^4.15.2",
    "instagram-node": "^0.5.8"
  },

**Comment by davidwkaiser** [comment]
OK, I've been working this some more. The problem seems to be that IG is returning an HTML file, not a JSON object. 

When I use this URL, I get JSON in return: 
https://api.instagram.com/v1/users/self/media/recent/?access_token=12345

but when the server makes a call using the instagram-node library, I get an HTML file, which yields the above error

**Comment by valentimmx** [comment]
@davidwkaiser did you find a way to solve this issue?

I'm taking too..

**Comment by davidwkaiser** [comment]
I have not
